### ISSUE TITLE
Tesh broken on Windows

### ISSUE THREAD

**Issue by agiersch** [simgrid/simgrid#255]
Tesh is broken on Windows since commit d6d20e218cd468880d8d8ae1046a291926597b18.
See https://ci.appveyor.com/project/mquinson/simgrid
```
Traceback (most recent call last):
  File "C:/projects/simgrid/bin/tesh", line 579, in <module>
    cmd.run_if_possible()
  File "C:/projects/simgrid/bin/tesh", line 264, in run_if_possible
    self._run()
  File "C:/projects/simgrid/bin/tesh", line 317, in _run
    proc = subprocess.Popen(args, bufsize=1, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True, preexec_fn=os.setsid)
AttributeError: module 'os' has no attribute 'setsid'
```

**Comment by agiersch** [comment]
Update error message after commit 69d7829d81bfeef39ee9b495dd2f3b5792e41ff6.
```
Traceback (most recent call last):
  File "C:/projects/simgrid/bin/tesh", line 581, in <module>
    cmd.run_if_possible()
  File "C:/projects/simgrid/bin/tesh", line 264, in run_if_possible
    self._run()
  File "C:/projects/simgrid/bin/tesh", line 319, in _run
    pgtokill = os.getpgid(proc.pid)
AttributeError: module 'os' has no attribute 'getpgid'
```

**Comment by mquinson** [comment]
This was fixed last night, but I forgot to close this bug from the commit log. Thus closing now.
